### ISSUE TITLE
Copyright Issue

### ISSUE THREAD

**Issue by FrancoisGrondin** [haoyu987/phasevocoder#1]
Hi,

I see that you are using copyrighted content (many figures in particular) directly from my website (guitarpitchshifter.com) without authorization. Please contact me so we can solve this issue: francois.grondin2@usherbrooke.ca

Best,

**Comment by haoyu987** [comment]
> 
> 
> Hi,
> 
> I see that you are using copyrighted content (many figures in particular) directly from my website (guitarpitchshifter.com) without authorization. Please contact me so we can solve this issue: [francois.grondin2@usherbrooke.ca](mailto:francois.grondin2@usherbrooke.ca)
> 
> Best,

Hi, Francois

This is a DSP course project from 2015. And I did this all by myself. All the references are listed in the doc/report.pdf. Maybe there are some coincidences.

Best.

**Comment by FrancoisGrondin** [comment]
Here are the pictures from my work on my website:

![Capture d’écran, le 2021-06-16 à 12 00 52](https://user-images.githubusercontent.com/4040041/122254142-d2b08000-ce9a-11eb-8bce-91e6b024b3f3.png)

![Capture d’écran, le 2021-06-16 à 12 00 41](https://user-images.githubusercontent.com/4040041/122254490-29b65500-ce9b-11eb-8092-bcce41795d82.png)

Here are the pictures from your repository:

![Capture d’écran, le 2021-06-16 à 12 00 15](https://user-images.githubusercontent.com/4040041/122254349-09869600-ce9b-11eb-8bf8-a9f53a1e8a49.png)

![Capture d’écran, le 2021-06-16 à 12 00 02](https://user-images.githubusercontent.com/4040041/122254362-0c818680-ce9b-11eb-9514-7189e37af085.png)

This does not look as some coincidences to me.

**Comment by haoyu987** [comment]
Sorry, I see now.
I did take these pictures somewhere when I did my project. But I don't
remember now.
Can I add your website in my reference?
Or if that is not OK to you, I will take down the project now.
Sorry about that.
